#!/usr/bin/env python3

"""
Convert a markdown file to pdf or (if requested) create a tex file

Configuration is possible
- in the header of the markdown file
- thru environment variable settings
- and command line arguments



Environment variables]

- `MD2PDF_TEMPLATE`: location of the template file
- `MD2PDF_LOGO`: location of the logo
- `MD2PDF_AUTHOR_EMAIL`: author's email
- `MD2PDF_COMPANY`: company name to use
- `MD2PDF_PDF_ENGINE`: specify PDF engine
- `MD2PDF_SYNTAX_DEFINITION_DIR`: specify directory containing
    additional syntax definition files
- `MD2PDF_HIGHLIGHT_STYLE`: specify a highlight style

Command line arguments

- `--template`: location of the template file
- `--logo`: location of the logo
- `--logo-width`: log width (default 40)
- `--company`: company name
- `--department`: department name
- `--highlight-style`: highlight style
- `--syntax-definition`: directory containing syntax definition files

Header of the markdown file

- the header is in YAML
- may contain the following values
    - `author`: required
    - `email`: optionalA_A~  !11111111111111111111111111111111111111spt<F4>jhl-===[]
    - `title`: required
    - `titlepage`: true or false (required)
    - `subtitle`: true or false (required)
    - `toc`: true or false (required)
    - `date`: required
"""

import os
import glob
import sys
import subprocess

from typing import List, Optional
from pathlib import Path

from datetime import date

import typer

import toml


__version__ = '1.1.2'



def version_callback(value: bool) -> None:
    """Print version information """

    if value:
        typer.echo(f'md2pdf Version: {__version__}')
        raise typer.Exit()


class PandocCmd:
    """Class to hold the pandoc command and its parameters

    Some parameters are simply hardcoded others can be set with

    - set_v: which sets `-V` parameters
    - set_m: which sets `-M` parameters
    - append: appends simple parameters
    - extend: adds a list of parameters

    """
    pandoc: List[str]

    def __init__(self, outfile: str) -> None:
        self.pandoc = [
            'pandoc',
            '-o',
            outfile,
            '-f',
            'markdown+smart',
            '--number-sections',
            '-M',
            'colorlinks=true',
            '-V',
            'linkcolor=ForestGreen',
            '-V',
            'classoption=oneside',
            '-V',
            'listings',
            '-M',
            'toc-own-page=true',
        ]

    def run(self) -> None:
        """Run pandoc command

        In case of error exit with return code 1
        """

        result = subprocess.run(self.pandoc, check=True).returncode
        if result:
            print(f'pandoc error: {result}')
            sys.exit(1)

    def set_v(self, varname: str, varval: Optional[str]) -> None:
        """Adds a `-V` parmeter.

        We check here if the parameter value is not None

        """

        if varval:
            self.pandoc.append('-V')
            self.pandoc.append(f'{varname}={varval}')

    def set_m(self, varname: str, varval: Optional[str]) -> None:
        """Adds a `-M` parmeter.

        We check here if the parameter value is not None

        """
        if varname:
            self.pandoc.append('-M')
            self.pandoc.append(f'{varname}={varval}')

    def append(self, argument: str) -> None:
        """Adds a single parmeter

        """
        self.pandoc.append(argument)

    def extend(self, mdfiles: List[str]) -> None:
        """Adds a list of parmeters

        """
        self.pandoc.extend(mdfiles)

def check_highlight_style(highlight_style: str) -> bool:
    """ Check if given highlight_style is supported by pandoc

        Returns False if not
    """

    valid_highlight_styles = [
        'pygments',
        'tango',
        'espresso',
        'zenburn',
        'kate',
        'monochrome',
        'breezedark',
        'haddock'
    ]

    if highlight_style in valid_highlight_styles:
        return True

    beauty_styles = ", ".join(valid_highlight_styles)
    print(f'Invalid highlight style {highlight_style} given. Must be one of: {beauty_styles}')
    sys.exit(1)

def add_syntax_definition(pdcmd: PandocCmd, syntax_definition_dir: str) -> None:
    """Adds all files *.xml in directory `syntax_definition_dir` as
        `--syntax-definition` parameter to invocation of pandoc
    """

    if not os.path.exists(syntax_definition_dir):
        print(f'syntax definition directory {syntax_definition_dir} does not exist')
        return

    filepattern = os.path.join(syntax_definition_dir, '*.xml')
    for xmlfile in glob.glob(filepattern):
        pdcmd.append('--syntax-definition')
        pdcmd.append(xmlfile)


def main(
    files: List[Path] = typer.Argument(default=None, dir_okay=False, exists=True),
    template: Optional[str] = typer.Option(
        None, '--template', help='Name of template file'
    ),
    logo: Optional[str] = typer.Option(None, '--logo', help='Name of logo file'),
    logo_width: Optional[str] = typer.Option(
        None, '--logo-width', help='Logo width (default 35mm)'
    ),
    highlight_style: Optional[str] = typer.Option(None, '--highlight-style',
        help='Specify coloring style to be used in highlighting source code'),
    syntax_definition: Optional[str] = typer.Option(None, '--syntax-definition',
        help='Specify a directory which contains syntax definition files'),
    no_toc: bool = typer.Option(
        False, '--no-toc', help='table of contents in PDF document'
    ),
    no_title: bool = typer.Option(False, '--no-title', help='title in PDF document'),
    tex_file: bool = typer.Option(
        False, '--tex', help='create TeX file instead of PDF document'
    ),
    company: Optional[str] = typer.Option(None, '--company', help='Name of company'),
    department: Optional[str] = typer.Option(
        None, '--department', help='Name of department'
    ),
    confidential: bool = typer.Option(
        False, '--confidential', help='indicate confidential'
    ),
    debug: bool = typer.Option(False, '--debug', help='turns debugging on'),
    pdf_engine: str = typer.Option(
        None,
        '--pdf-engine',
        help='Specify pdf engine, one of lualatex, xelatex or tectonic ',
    ),
    _version: bool = typer.Option(
        None, '-V', '--version', callback=version_callback, help='Show version and exit'
    ),
):
    """Create a PDF file from one or more markdown files"""

    if not files:
        typer.echo('Error: Must specify at least one .md file.')
        raise typer.Abort()

    mdfiles: List[str] = [str(md) for md in files]

    template = template or os.environ.get('MD2PDF_TEMPLATE')
    if template is None:
        print('No template specified')
        sys.exit(1)

    email = os.environ.get('MD2PDF_AUTHOR_EMAIL')
    footer_center = ''

    # command line overwrites `MD2PDF_PDF_ENGINE`. if both are not given
    # then `xelatex` is the default
    pdf_engine = pdf_engine or os.environ.get('MD2PDF_PDF_ENGINE') or 'xelatex'
    # check that pdf-engine is one of the following
    if pdf_engine not in ['xelatex', 'lualatex', 'tectonic']:
        print('--pdf-engine must be one of "xelatex", "lualatex", "tectonic"')
        sys.exit(1)

    ext = '.pdf'
    if tex_file:
        ext = '.tex'

    if len(mdfiles) == 1:
        toml_file = os.path.splitext(mdfiles[0])[0] + '.toml'

        if os.path.exists(toml_file):
            print(f'TOML file {toml_file} found')
            parsed_toml = toml.load(toml_file)
            default_val = parsed_toml.get('default')
            if default_val is None:
                print(f'No file names found in {toml_file}')
            else:
                mdfiles = default_val.get('files')

    for mdf in mdfiles:
        print(f'Compiling {mdf}')

    main_mdfile = os.path.realpath(mdfiles[0])

    outfile = Path(main_mdfile).stem + ext

    year = date.today().year

    company = company or os.environ.get('MD2PDF_COMPANY')
    department = department or os.environ.get('MD2PDF_DEPARTMENT')

    if company:
        if confidential:
            footer_center = f'© Copyright {year} {company}'
        else:
            footer_center = f'{year} {company}'

    pdcmd = PandocCmd(outfile)
    pdcmd.append(f'--template={template}')
    pdcmd.append(f'--pdf-engine={pdf_engine}')

    pdcmd.set_v('footer-center', footer_center)
    pdcmd.set_v('company', company)
    pdcmd.set_v('department', department)

    syntax_definition = syntax_definition or os.environ.get('MD2PDF_SYNTAX_DEFINITION_DIR')
    if syntax_definition is not None:
        add_syntax_definition(pdcmd, syntax_definition)

    pdcmd.append('--highlight-style')
    highlight_style = highlight_style or os.environ.get('MD2PDF_HIGHLIGHT_STYLE')
    if highlight_style is None:
        pdcmd.append('pygments')
    else:
        check_highlight_style(highlight_style)
        pdcmd.append(highlight_style)

    if no_title:
        pdcmd.set_m('titlepage', 'false')

    logo = logo or os.environ.get('MD2PDF_LOGO')
    pdcmd.set_v('logo', logo)

    logo_width = logo_width or os.environ.get('MD2PDF_LOGO_WIDTH')
    pdcmd.set_v('logo-width', logo_width)

    pdcmd.set_v('email', email)

    if not no_toc:
        pdcmd.append('--toc')

    pdcmd.extend(mdfiles)

    if debug:
        print(' '.join(pdcmd.pandoc))


    pdcmd.run()


if __name__ == '__main__':
    typer.run(main)
